/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfacesSol from "./interfaces.sol";
export type { interfacesSol };
export type { MockERC20 } from "./MockERC20";
export type { MockThorchainRouter } from "./MockThorchainRouter";
export type { MockTradeLayerIngress } from "./MockTradeLayerIngress";
export type { MockUTXORegistry } from "./MockUTXORegistry";
export type { TemplateBoundThorchainDepositAdapter } from "./TemplateBoundThorchainDepositAdapter";
export type { ThorchainDepositAdapter } from "./ThorchainDepositAdapter";
