/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TemplateBoundThorchainDepositAdapterInterface
  extends Interface {
  getFunction(
    nameOrSignature:
      | "NATIVE_ASSET"
      | "computeDepositId"
      | "depositErc20WithTemplate"
      | "depositNativeWithTemplate"
      | "depositorNonces"
      | "owner"
      | "router"
      | "templateBoundDeposits"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TemplateBoundSwapCommitted"
      | "ThorDepositRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "NATIVE_ASSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeDepositId",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositErc20WithTemplate",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNativeWithTemplate",
    values: [
      AddressLike,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositorNonces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "templateBoundDeposits",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "NATIVE_ASSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeDepositId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositErc20WithTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositNativeWithTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositorNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "templateBoundDeposits",
    data: BytesLike
  ): Result;
}

export namespace TemplateBoundSwapCommittedEvent {
  export type InputTuple = [
    depositId: BytesLike,
    depositor: AddressLike,
    asset: AddressLike,
    templateHash: BytesLike,
    destinationScriptCommitment: BytesLike,
    thorMemoHash: BytesLike,
    destinationChain: BigNumberish,
    receiptPropertyId: BigNumberish,
    collateralPropertyId: BigNumberish,
    settlementState: BigNumberish,
    nonce: BigNumberish,
    amount: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    depositId: string,
    depositor: string,
    asset: string,
    templateHash: string,
    destinationScriptCommitment: string,
    thorMemoHash: string,
    destinationChain: bigint,
    receiptPropertyId: bigint,
    collateralPropertyId: bigint,
    settlementState: bigint,
    nonce: bigint,
    amount: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    depositId: string;
    depositor: string;
    asset: string;
    templateHash: string;
    destinationScriptCommitment: string;
    thorMemoHash: string;
    destinationChain: bigint;
    receiptPropertyId: bigint;
    collateralPropertyId: bigint;
    settlementState: bigint;
    nonce: bigint;
    amount: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThorDepositRequestedEvent {
  export type InputTuple = [
    sender: AddressLike,
    vault: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    memo: string,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    vault: string,
    asset: string,
    amount: bigint,
    memo: string,
    expiry: bigint
  ];
  export interface OutputObject {
    sender: string;
    vault: string;
    asset: string;
    amount: bigint;
    memo: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TemplateBoundThorchainDepositAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): TemplateBoundThorchainDepositAdapter;
  waitForDeployment(): Promise<this>;

  interface: TemplateBoundThorchainDepositAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NATIVE_ASSET: TypedContractMethod<[], [string], "view">;

  computeDepositId: TypedContractMethod<
    [
      depositor: AddressLike,
      nonce: BigNumberish,
      templateHash: BytesLike,
      destinationScriptCommitment: BytesLike,
      thorMemoHash: BytesLike
    ],
    [string],
    "view"
  >;

  depositErc20WithTemplate: TypedContractMethod<
    [
      vault: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish,
      templateHash: BytesLike,
      destinationScriptCommitment: BytesLike,
      destinationChain: BigNumberish,
      receiptPropertyId: BigNumberish,
      collateralPropertyId: BigNumberish,
      settlementState: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  depositNativeWithTemplate: TypedContractMethod<
    [
      vault: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish,
      templateHash: BytesLike,
      destinationScriptCommitment: BytesLike,
      destinationChain: BigNumberish,
      receiptPropertyId: BigNumberish,
      collateralPropertyId: BigNumberish,
      settlementState: BigNumberish
    ],
    [string],
    "payable"
  >;

  depositorNonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  router: TypedContractMethod<[], [string], "view">;

  templateBoundDeposits: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        depositor: string;
        vault: string;
        asset: string;
        amount: bigint;
        templateHash: string;
        destinationScriptCommitment: string;
        thorMemoHash: string;
        destinationChain: bigint;
        receiptPropertyId: bigint;
        collateralPropertyId: bigint;
        settlementState: bigint;
        nonce: bigint;
        expiry: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NATIVE_ASSET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "computeDepositId"
  ): TypedContractMethod<
    [
      depositor: AddressLike,
      nonce: BigNumberish,
      templateHash: BytesLike,
      destinationScriptCommitment: BytesLike,
      thorMemoHash: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositErc20WithTemplate"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish,
      templateHash: BytesLike,
      destinationScriptCommitment: BytesLike,
      destinationChain: BigNumberish,
      receiptPropertyId: BigNumberish,
      collateralPropertyId: BigNumberish,
      settlementState: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositNativeWithTemplate"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish,
      templateHash: BytesLike,
      destinationScriptCommitment: BytesLike,
      destinationChain: BigNumberish,
      receiptPropertyId: BigNumberish,
      collateralPropertyId: BigNumberish,
      settlementState: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositorNonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "templateBoundDeposits"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        depositor: string;
        vault: string;
        asset: string;
        amount: bigint;
        templateHash: string;
        destinationScriptCommitment: string;
        thorMemoHash: string;
        destinationChain: bigint;
        receiptPropertyId: bigint;
        collateralPropertyId: bigint;
        settlementState: bigint;
        nonce: bigint;
        expiry: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TemplateBoundSwapCommitted"
  ): TypedContractEvent<
    TemplateBoundSwapCommittedEvent.InputTuple,
    TemplateBoundSwapCommittedEvent.OutputTuple,
    TemplateBoundSwapCommittedEvent.OutputObject
  >;
  getEvent(
    key: "ThorDepositRequested"
  ): TypedContractEvent<
    ThorDepositRequestedEvent.InputTuple,
    ThorDepositRequestedEvent.OutputTuple,
    ThorDepositRequestedEvent.OutputObject
  >;

  filters: {
    "TemplateBoundSwapCommitted(bytes32,address,address,bytes32,bytes32,bytes32,uint32,uint32,uint32,uint32,uint64,uint256,uint256)": TypedContractEvent<
      TemplateBoundSwapCommittedEvent.InputTuple,
      TemplateBoundSwapCommittedEvent.OutputTuple,
      TemplateBoundSwapCommittedEvent.OutputObject
    >;
    TemplateBoundSwapCommitted: TypedContractEvent<
      TemplateBoundSwapCommittedEvent.InputTuple,
      TemplateBoundSwapCommittedEvent.OutputTuple,
      TemplateBoundSwapCommittedEvent.OutputObject
    >;

    "ThorDepositRequested(address,address,address,uint256,string,uint256)": TypedContractEvent<
      ThorDepositRequestedEvent.InputTuple,
      ThorDepositRequestedEvent.OutputTuple,
      ThorDepositRequestedEvent.OutputObject
    >;
    ThorDepositRequested: TypedContractEvent<
      ThorDepositRequestedEvent.InputTuple,
      ThorDepositRequestedEvent.OutputTuple,
      ThorDepositRequestedEvent.OutputObject
    >;
  };
}
