/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockTradeLayerIngressInterface extends Interface {
  getFunction(nameOrSignature: "absorbUtxoRef" | "absorbed"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "UtxoAbsorbed"): EventFragment;

  encodeFunctionData(
    functionFragment: "absorbUtxoRef",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "absorbed",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "absorbUtxoRef",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "absorbed", data: BytesLike): Result;
}

export namespace UtxoAbsorbedEvent {
  export type InputTuple = [
    utxoRef: BytesLike,
    sats: BigNumberish,
    extraData: BytesLike
  ];
  export type OutputTuple = [utxoRef: string, sats: bigint, extraData: string];
  export interface OutputObject {
    utxoRef: string;
    sats: bigint;
    extraData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockTradeLayerIngress extends BaseContract {
  connect(runner?: ContractRunner | null): MockTradeLayerIngress;
  waitForDeployment(): Promise<this>;

  interface: MockTradeLayerIngressInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  absorbUtxoRef: TypedContractMethod<
    [utxoRef: BytesLike, sats: BigNumberish, extraData: BytesLike],
    [void],
    "nonpayable"
  >;

  absorbed: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint] & {
        utxoRef: string;
        sats: bigint;
        extraData: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "absorbUtxoRef"
  ): TypedContractMethod<
    [utxoRef: BytesLike, sats: BigNumberish, extraData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "absorbed"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint] & {
        utxoRef: string;
        sats: bigint;
        extraData: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "UtxoAbsorbed"
  ): TypedContractEvent<
    UtxoAbsorbedEvent.InputTuple,
    UtxoAbsorbedEvent.OutputTuple,
    UtxoAbsorbedEvent.OutputObject
  >;

  filters: {
    "UtxoAbsorbed(bytes32,uint64,bytes)": TypedContractEvent<
      UtxoAbsorbedEvent.InputTuple,
      UtxoAbsorbedEvent.OutputTuple,
      UtxoAbsorbedEvent.OutputObject
    >;
    UtxoAbsorbed: TypedContractEvent<
      UtxoAbsorbedEvent.InputTuple,
      UtxoAbsorbedEvent.OutputTuple,
      UtxoAbsorbedEvent.OutputObject
    >;
  };
}
