/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockThorchainRouterInterface extends Interface {
  getFunction(nameOrSignature: "depositWithExpiry"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DepositObserved"): EventFragment;

  encodeFunctionData(
    functionFragment: "depositWithExpiry",
    values: [AddressLike, AddressLike, BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositWithExpiry",
    data: BytesLike
  ): Result;
}

export namespace DepositObservedEvent {
  export type InputTuple = [
    vault: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    memo: string,
    expiry: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    asset: string,
    amount: bigint,
    memo: string,
    expiry: bigint,
    value: bigint
  ];
  export interface OutputObject {
    vault: string;
    asset: string;
    amount: bigint;
    memo: string;
    expiry: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockThorchainRouter extends BaseContract {
  connect(runner?: ContractRunner | null): MockThorchainRouter;
  waitForDeployment(): Promise<this>;

  interface: MockThorchainRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositWithExpiry: TypedContractMethod<
    [
      vault: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositWithExpiry"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish
    ],
    [void],
    "payable"
  >;

  getEvent(
    key: "DepositObserved"
  ): TypedContractEvent<
    DepositObservedEvent.InputTuple,
    DepositObservedEvent.OutputTuple,
    DepositObservedEvent.OutputObject
  >;

  filters: {
    "DepositObserved(address,address,uint256,string,uint256,uint256)": TypedContractEvent<
      DepositObservedEvent.InputTuple,
      DepositObservedEvent.OutputTuple,
      DepositObservedEvent.OutputObject
    >;
    DepositObserved: TypedContractEvent<
      DepositObservedEvent.InputTuple,
      DepositObservedEvent.OutputTuple,
      DepositObservedEvent.OutputObject
    >;
  };
}
