/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockUTXORegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "computeRef" | "markSpent" | "register" | "utxos"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Registered" | "Spent"): EventFragment;

  encodeFunctionData(
    functionFragment: "computeRef",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markSpent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "utxos", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "computeRef", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markSpent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "utxos", data: BytesLike): Result;
}

export namespace RegisteredEvent {
  export type InputTuple = [
    utxoRef: BytesLike,
    txid: BytesLike,
    vout: BigNumberish,
    sats: BigNumberish,
    owner: AddressLike
  ];
  export type OutputTuple = [
    utxoRef: string,
    txid: string,
    vout: bigint,
    sats: bigint,
    owner: string
  ];
  export interface OutputObject {
    utxoRef: string;
    txid: string;
    vout: bigint;
    sats: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpentEvent {
  export type InputTuple = [utxoRef: BytesLike, spender: AddressLike];
  export type OutputTuple = [utxoRef: string, spender: string];
  export interface OutputObject {
    utxoRef: string;
    spender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockUTXORegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MockUTXORegistry;
  waitForDeployment(): Promise<this>;

  interface: MockUTXORegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computeRef: TypedContractMethod<
    [txid: BytesLike, vout: BigNumberish],
    [string],
    "view"
  >;

  markSpent: TypedContractMethod<[utxoRef: BytesLike], [void], "nonpayable">;

  register: TypedContractMethod<
    [
      txid: BytesLike,
      vout: BigNumberish,
      sats: BigNumberish,
      owner: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  utxos: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, boolean] & {
        txid: string;
        vout: bigint;
        sats: bigint;
        owner: string;
        spent: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computeRef"
  ): TypedContractMethod<
    [txid: BytesLike, vout: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "markSpent"
  ): TypedContractMethod<[utxoRef: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [
      txid: BytesLike,
      vout: BigNumberish,
      sats: BigNumberish,
      owner: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "utxos"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, boolean] & {
        txid: string;
        vout: bigint;
        sats: bigint;
        owner: string;
        spent: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "Registered"
  ): TypedContractEvent<
    RegisteredEvent.InputTuple,
    RegisteredEvent.OutputTuple,
    RegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Spent"
  ): TypedContractEvent<
    SpentEvent.InputTuple,
    SpentEvent.OutputTuple,
    SpentEvent.OutputObject
  >;

  filters: {
    "Registered(bytes32,bytes32,uint32,uint64,address)": TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
    Registered: TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;

    "Spent(bytes32,address)": TypedContractEvent<
      SpentEvent.InputTuple,
      SpentEvent.OutputTuple,
      SpentEvent.OutputObject
    >;
    Spent: TypedContractEvent<
      SpentEvent.InputTuple,
      SpentEvent.OutputTuple,
      SpentEvent.OutputObject
    >;
  };
}
