/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ThorchainDepositAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "NATIVE_ASSET"
      | "depositErc20"
      | "depositNative"
      | "owner"
      | "router"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ThorDepositRequested"): EventFragment;

  encodeFunctionData(
    functionFragment: "NATIVE_ASSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositErc20",
    values: [AddressLike, AddressLike, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNative",
    values: [AddressLike, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "NATIVE_ASSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositErc20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
}

export namespace ThorDepositRequestedEvent {
  export type InputTuple = [
    sender: AddressLike,
    vault: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    memo: string,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    vault: string,
    asset: string,
    amount: bigint,
    memo: string,
    expiry: bigint
  ];
  export interface OutputObject {
    sender: string;
    vault: string;
    asset: string;
    amount: bigint;
    memo: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ThorchainDepositAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): ThorchainDepositAdapter;
  waitForDeployment(): Promise<this>;

  interface: ThorchainDepositAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NATIVE_ASSET: TypedContractMethod<[], [string], "view">;

  depositErc20: TypedContractMethod<
    [
      vault: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  depositNative: TypedContractMethod<
    [
      vault: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish
    ],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  router: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NATIVE_ASSET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositErc20"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositNative"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      amount: BigNumberish,
      memo: string,
      expiry: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ThorDepositRequested"
  ): TypedContractEvent<
    ThorDepositRequestedEvent.InputTuple,
    ThorDepositRequestedEvent.OutputTuple,
    ThorDepositRequestedEvent.OutputObject
  >;

  filters: {
    "ThorDepositRequested(address,address,address,uint256,string,uint256)": TypedContractEvent<
      ThorDepositRequestedEvent.InputTuple,
      ThorDepositRequestedEvent.OutputTuple,
      ThorDepositRequestedEvent.OutputObject
    >;
    ThorDepositRequested: TypedContractEvent<
      ThorDepositRequestedEvent.InputTuple,
      ThorDepositRequestedEvent.OutputTuple,
      ThorDepositRequestedEvent.OutputObject
    >;
  };
}
