/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITradeLayerIngress,
  ITradeLayerIngressInterface,
} from "../../../contracts/interfaces.sol/ITradeLayerIngress";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "utxoRef",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "sats",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "extraData",
        type: "bytes",
      },
    ],
    name: "absorbUtxoRef",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITradeLayerIngress__factory {
  static readonly abi = _abi;
  static createInterface(): ITradeLayerIngressInterface {
    return new Interface(_abi) as ITradeLayerIngressInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITradeLayerIngress {
    return new Contract(address, _abi, runner) as unknown as ITradeLayerIngress;
  }
}
