/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IThorchainRouter,
  IThorchainRouterInterface,
} from "../../../contracts/interfaces.sol/IThorchainRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "vault",
        type: "address",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "memo",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
    ],
    name: "depositWithExpiry",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IThorchainRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IThorchainRouterInterface {
    return new Interface(_abi) as IThorchainRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IThorchainRouter {
    return new Contract(address, _abi, runner) as unknown as IThorchainRouter;
  }
}
