/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockThorchainRouter,
  MockThorchainRouterInterface,
} from "../../contracts/MockThorchainRouter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "vault",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "memo",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "DepositObserved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "vault",
        type: "address",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "memo",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
    ],
    name: "depositWithExpiry",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610131908161001c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c6344bc937b14602857600080fd5b60a036600319011260f7576001600160a01b0390600435828116919082900360f35760243592831680930360f3576064359067ffffffffffffffff80831160ef573660238401121560ef57826004013590811160ef57366024828501011160ef57818160a09260247f7189b319ccf5c42f7b934a6d5ca8c1cc9fbf2d49d26e0e90d644ab13ed95840d96604435855260806020860152826080860152018484013781810183018890526084356040830152346060830152601f01601f19168101030190a380f35b8580fd5b8380fd5b5080fdfea264697066735822122022d6c6d999afd98181650b11fd1bc20fa7f0c61b91824f9b40c3fb01d8cd7e8164736f6c63430008180033";

type MockThorchainRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockThorchainRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockThorchainRouter__factory extends ContractFactory {
  constructor(...args: MockThorchainRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockThorchainRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockThorchainRouter__factory {
    return super.connect(runner) as MockThorchainRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockThorchainRouterInterface {
    return new Interface(_abi) as MockThorchainRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockThorchainRouter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockThorchainRouter;
  }
}
